### ISSUE TITLE
GET /index/ Listing files API change

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Files#15]
Params like 
* folder 
* page
* perPage 

must be send as `query` params as you cannot post any body with `GET` request 

<img width="1552" alt="Screenshot 2021-05-05 at 16 45 04" src="https://user-images.githubusercontent.com/214608/117160490-6f263380-adc1-11eb-9b66-fdedf67acd29.png">

**Comment by shdpl** [comment]
I know it's cross-ticket, but I already realized that in https://github.com/EscolaLMS/Files/pull/11
