### ISSUE TITLE
index GET endpoint

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Files#2]
see https://github.com/EscolaLMS/Files/discussions for details 

- [x] listing files for main folder 
- [x] listing files for given folder 
- [x] tests (with mock files) - you can copy settings from here https://github.com/EscolaLMS/H5P/blob/main/tests/Api/LibraryApiTest.php
- [x] swagger, see here https://github.com/EscolaLMS/H5P/tree/main/src/Http/Controllers

**Comment by qunabu** [comment]
List should be paginated with standard Laravel pagination https://laravel.com/docs/8.x/pagination

**Comment by shdpl** [comment]
Please check the https://github.com/EscolaLMS/Files/pull/10
