### ISSUE TITLE
upload POST

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Files#3]
see https://github.com/EscolaLMS/Files/discussions for details 

- [x] upload one file for main folder 
- [x] upload many files for main folder 
- [x] upload one file  for given folder 
- [x] upload many files for given folder 
- [ ] listing files for given folder 
- [x] tests (with mock files) - you can copy settings from here https://github.com/EscolaLMS/H5P/blob/main/tests/Api/LibraryApiTest.php
- [x] swagger, see here https://github.com/EscolaLMS/H5P/tree/main/src/Http/Controllers

**Comment by shdpl** [comment]
shall we close this? https://github.com/EscolaLMS/Files/pull/7
