### ISSUE TITLE
delete DELETE file

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Files#5]
- [x] delete file 
- [x] tests (with mock files) - you can copy settings from here https://github.com/EscolaLMS/H5P/blob/main/tests/Api/LibraryApiTest.php
- [x] swagger, see here https://github.com/EscolaLMS/H5P/tree/main/src/Http/Controllers

**Comment by shdpl** [comment]
Please check https://github.com/EscolaLMS/Files/pull/12
